spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schedule?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: schedule
    password: kimsungmin1!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
